apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      containers:
      - name: jupyterlab
        image: jupyterlab-custom:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: jupyter-data
          mountPath: /home/jovyan/work
      volumes:
      - name: jupyter-data
        persistentVolumeClaim:
          claimName: jupyter-pvc