apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-ui
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-ui
  template:
    metadata:
      labels:
        app: streamlit-ui
    spec:
      containers:
        - name: streamlit-ui
          image: localhost:32000/streamlit-ui:latest
          ports:
            - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-ui
  namespace: loadtest
spec:
  type: NodePort
  selector:
    app: streamlit-ui
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30081
